import type { CalendarEvent } from './types'

/**
 * Datos de demostración alineados al dominio real de la plataforma:
 * catálogo actividad → sub_actividad (migración 20260826140000_f1_visitas.sql)
 * y cartera de personas del asesor. Sin datos del template original.
 */

export const INITIAL_ATTENDEES = [
  { id: '1', name: 'Luisa Fernanda Roldán', initials: 'LR', role: 'Asesora de Crédito', avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face' },
  { id: '2', name: 'Erick Bardales', initials: 'EB', role: 'Supervisor de Zona', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face' },
  { id: '3', name: 'Ana Lucía Perén', initials: 'AP', role: 'Analista de Riesgo', avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face' },
  { id: '4', name: 'Marco Tulio Méndez', initials: 'MM', role: 'Asesor de Campo', avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face' },
]

export const CATALOGO_ACTIVIDADES: { id: number; nombre: string; sub_actividades: { id: number; nombre: string }[] }[] = [
  {
    id: 1,
    nombre: 'Verificación de garantías',
    sub_actividades: [
      { id: 11, nombre: 'Inspección prendaria' },
      { id: 12, nombre: 'Verificación de activos' },
      { id: 13, nombre: 'Revisión de documentos' },
    ],
  },
  {
    id: 2,
    nombre: 'Seguimiento de crédito',
    sub_actividades: [
      { id: 21, nombre: 'Revisión de estado de cuenta' },
      { id: 22, nombre: 'Renegociación de cuota' },
      { id: 23, nombre: 'Verificación de uso de fondos' },
    ],
  },
  {
    id: 3,
    nombre: 'Prospección de cliente',
    sub_actividades: [
      { id: 31, nombre: 'Levantamiento de ficha' },
      { id: 32, nombre: 'Presentación de producto' },
    ],
  },
  {
    id: 4,
    nombre: 'Recuperación de cartera',
    sub_actividades: [
      { id: 41, nombre: 'Aviso de mora' },
      { id: 42, nombre: 'Acuerdo de pago' },
      { id: 43, nombre: 'Recuperación judicial' },
    ],
  },
  {
    id: 5,
    nombre: 'Inspección de cultivo',
    sub_actividades: [
      { id: 51, nombre: 'Medición de hectáreas' },
      { id: 52, nombre: 'Estado fenológico' },
    ],
  },
]

export const CATALOGO_HORAS = [
  { id: 1, nombre: '30 minutos', cantidad: 0.5 },
  { id: 2, nombre: '1 hora', cantidad: 1.0 },
  { id: 3, nombre: '2 horas', cantidad: 2.0 },
  { id: 4, nombre: '4 horas', cantidad: 4.0 },
  { id: 5, nombre: 'Jornada completa', cantidad: 8.0 },
]

export const INITIAL_EVENTS: CalendarEvent[] = [
  // SEP 14 — visita de verificación (pantalla de detalle del template)
  {
    id: 'vis-1001',
    title: 'Verificación de garantías — Agrícola El Roble',
    date: '2026-09-14',
    startTime: '08:30',
    endTime: '10:00',
    category: 'lavender',
    location: 'Km 42 Carretera al Pacífico, Escuintla',
    videoCall: 'meet.google.com/gc-robles-vi',
    notes: 'Inspección prendaria de 2 tractores y verificación de documentos de propiedad. Recordar llevar cámara para el registro fotográfico.',
    attendees: [INITIAL_ATTENDEES[0], INITIAL_ATTENDEES[2]],
    reminder: '20 mins before',
    personaId: 'p-101',
    personaName: 'Agrícola El Roble S.A.',
    actividadId: 1,
    subActividadId: 11,
    estado: 'programada',
  },
  {
    id: 'vis-1002',
    title: 'Seguimiento de crédito — Distribuidora La Bendición',
    date: '2026-09-14',
    startTime: '11:00',
    endTime: '12:00',
    category: 'amber',
    location: '4a Calle 12-45 Zona 3, Quetzaltenango',
    notes: 'Revisión de estado de cuenta y renegociación de cuota #14.',
    attendees: [INITIAL_ATTENDEES[1]],
    reminder: '30 mins before',
    personaId: 'p-102',
    personaName: 'Distribuidora La Bendición',
    actividadId: 2,
    subActividadId: 22,
    estado: 'programada',
  },

  // SEP 16
  {
    id: 'vis-1003',
    title: 'Prospección — Cooperativa Agrícola San Pedro',
    date: '2026-09-16',
    startTime: '09:00',
    endTime: '10:30',
    category: 'mint',
    location: 'San Pedro Carchá, Alta Verapaz',
    notes: 'Levantamiento de ficha de socio y presentación del producto de crédito agrícola.',
    attendees: [INITIAL_ATTENDEES[0], INITIAL_ATTENDEES[3]],
    reminder: '1 hour before',
    personaId: 'p-104',
    personaName: 'Cooperativa Agrícola San Pedro',
    actividadId: 3,
    subActividadId: 31,
    estado: 'programada',
  },
  {
    id: 'vis-1004',
    title: 'Recuperación de cartera — Comercial El Progreso',
    date: '2026-09-16',
    startTime: '14:30',
    endTime: '15:30',
    category: 'rose',
    location: '7a Avenida 6-20 Zona 1, Cobán',
    notes: 'Aviso de mora (45 días) y búsqueda de acuerdo de pago.',
    attendees: [INITIAL_ATTENDEES[3]],
    reminder: '30 mins before',
    personaId: 'p-105',
    personaName: 'Comercial El Progreso',
    actividadId: 4,
    subActividadId: 41,
    estado: 'programada',
  },
  {
    id: 'vis-1005',
    title: 'Inspección de cultivo — Finca Santa Isabel',
    date: '2026-09-16',
    startTime: '16:00',
    endTime: '18:00',
    category: 'sky',
    location: 'Aldea Panzós, Valle del Polochic',
    notes: 'Medición de 12 hectáreas de maíz y evaluación de estado fenológico previo a cosecha.',
    attendees: [INITIAL_ATTENDEES[2]],
    reminder: '1 hour before',
    personaId: 'p-106',
    personaName: 'Finca Santa Isabel',
    actividadId: 5,
    subActividadId: 51,
    estado: 'programada',
  },

  // SEP 17 — día activo en la vista Timeline (pantalla central del template)
  {
    id: 'vis-1006',
    title: 'Verificación de garantías — Agropecuaria El Triunfo',
    date: '2026-09-17',
    startTime: '08:30',
    endTime: '10:00',
    category: 'amber',
    location: 'Km 56 Carretera a Puerto San José, Escuintla',
    notes: 'Verificación de activos: 4 cabezas de ganado y equipo de riego. Cruce con registro fotográfico.',
    attendees: [INITIAL_ATTENDEES[1], INITIAL_ATTENDEES[2]],
    reminder: '10 mins before',
    personaId: 'p-107',
    personaName: 'Agropecuaria El Triunfo',
    actividadId: 1,
    subActividadId: 12,
    estado: 'programada',
  },
  {
    id: 'vis-1007',
    title: 'Seguimiento de crédito — Farmacia Santa María',
    date: '2026-09-17',
    startTime: '10:15',
    endTime: '11:45',
    category: 'lavender',
    videoCall: 'meet.google.com/gc-santamaria',
    location: 'Avenida Elena 8-30 Zona 1, Guatemala',
    notes: 'Revisión de estado de cuenta y verificación de uso de fondos (ampliación de local).',
    attendees: INITIAL_ATTENDEES,
    reminder: '15 mins before',
    personaId: 'p-103',
    personaName: 'Farmacia Santa María',
    actividadId: 2,
    subActividadId: 23,
    estado: 'programada',
  },
  {
    id: 'vis-1008',
    title: 'Prospección — Distribuidora Los Altos',
    date: '2026-09-17',
    startTime: '13:00',
    endTime: '14:45',
    category: 'mint',
    location: 'Calzada Roosevelt 22-10 Zona 11, Guatemala',
    notes: 'Presentación de producto y cotización de línea de crédito de Q 80,000.',
    attendees: [INITIAL_ATTENDEES[0], INITIAL_ATTENDEES[3]],
    reminder: '30 mins before',
    personaId: 'p-108',
    personaName: 'Distribuidora Los Altos',
    actividadId: 3,
    subActividadId: 32,
    estado: 'programada',
  },
  {
    id: 'vis-1009',
    title: 'Recuperación de cartera — Tienda La Bendición',
    date: '2026-09-17',
    startTime: '15:30',
    endTime: '17:00',
    category: 'rose',
    location: '5a Calle 3-18 Zona 2, Mixco',
    notes: 'Acuerdo de pago propuesto: abono inicial Q 5,000 y plan a 6 cuotas.',
    attendees: [INITIAL_ATTENDEES[3]],
    reminder: '1 hour before',
    personaId: 'p-109',
    personaName: 'Tienda La Bendición',
    actividadId: 4,
    subActividadId: 42,
    estado: 'programada',
  },

  // OCT 7
  {
    id: 'vis-1010',
    title: 'Inspección de cultivo — Agrícola Chiviténango',
    date: '2026-10-07',
    startTime: '09:00',
    endTime: '11:00',
    category: 'sky',
    location: 'Cantón Chiviténango, Totonicapán',
    notes: 'Estado fenológico de parcela de trigo (0.8 hectáreas) y verificación de producción estimada.',
    attendees: [INITIAL_ATTENDEES[2]],
    reminder: '1 day before',
    personaId: 'p-110',
    personaName: 'Agrícola Chiviténango',
    actividadId: 5,
    subActividadId: 52,
    estado: 'programada',
  },

  // NOV 23
  {
    id: 'vis-1011',
    title: 'Verificación de garantías — Transportes El Norte',
    date: '2026-11-23',
    startTime: '15:30',
    endTime: '16:30',
    category: 'amber',
    location: 'Ruta al Atlántico Km 85, El Progreso',
    notes: 'Revisión de documentos del camión Freightliner (prenda) y póliza de seguro vigente.',
    attendees: [INITIAL_ATTENDEES[1]],
    reminder: '15 mins before',
    personaId: 'p-111',
    personaName: 'Transportes El Norte',
    actividadId: 1,
    subActividadId: 13,
    estado: 'programada',
  },
  {
    id: 'vis-1012',
    title: 'Recuperación judicial — Comercial San Gabriel',
    date: '2026-11-23',
    startTime: '19:00',
    endTime: '22:00',
    category: 'rose',
    location: 'Juzgado de Instancia Civil, Quetzaltenango',
    notes: 'Audiencia de reconocimiento de firma y contenido con el abogado externo.',
    attendees: [INITIAL_ATTENDEES[1], INITIAL_ATTENDEES[2]],
    reminder: '2 hours before',
    personaId: 'p-112',
    personaName: 'Comercial San Gabriel',
    actividadId: 4,
    subActividadId: 43,
    estado: 'programada',
  },

  // DIC 1
  {
    id: 'vis-1013',
    title: 'Gira de cierre anual — Zona Sur',
    date: '2026-12-01',
    startTime: '08:00',
    endTime: '18:00',
    category: 'sky',
    location: 'Tiquisate, La Democracia, Chiquimulilla (Santa Rosa)',
    notes: 'Ruta de cierre con 6 clientes de la zona: verificación de garantías y acuerdos de renovación 2027.',
    attendees: INITIAL_ATTENDEES,
    reminder: '1 day before',
    personaId: 'p-113',
    personaName: 'Cartera Zona Sur (6 clientes)',
    actividadId: 1,
    subActividadId: 12,
    estado: 'programada',
  },
]
