import type { CalendarEvent } from './types'

export const INITIAL_ATTENDEES = [
  { id: '1', name: 'Sofía Morales', initials: 'SM', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face' },
  { id: '2', name: 'Carlos Ruiz', initials: 'CR', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face' },
  { id: '3', name: 'Elena Gómez', initials: 'EG', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face' },
  { id: '4', name: 'David Lee', initials: 'DL', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face' },
]

export const INITIAL_EVENTS: CalendarEvent[] = [
  // SEP 14 - Evento principal de detalle
  {
    id: 'ev-14-1',
    title: 'Annual alumni lunch',
    date: '2026-09-14',
    startTime: '13:20',
    endTime: '16:00',
    category: 'lavender',
    location: "Ginn's Coffee Club",
    videoCall: 'Zoom - 0366971',
    notes: 'Remember to bring camera for the annual group photo',
    attendees: INITIAL_ATTENDEES,
    reminder: '20 mins before',
    personaName: 'Asociación Alumni GT',
  },

  // SEP 16
  {
    id: 'ev-16-1',
    title: 'Alumni lunch',
    date: '2026-09-16',
    startTime: '12:00',
    endTime: '14:00',
    category: 'amber',
    location: 'Club Campestre Guatemala',
    notes: 'Reunión de coordinación y revisión de fondos',
    attendees: [INITIAL_ATTENDEES[0], INITIAL_ATTENDEES[1]],
    reminder: '15 mins before',
  },
  {
    id: 'ev-16-2',
    title: 'Make an appointment - Dentist',
    date: '2026-09-16',
    startTime: '14:30',
    endTime: '15:30',
    category: 'mint',
    location: 'Clínica Dental Zona 10',
    notes: 'Limpieza semestral de rutina',
    reminder: '1 hour before',
  },
  {
    id: 'ev-16-3',
    title: 'Book travel tickets',
    date: '2026-09-16',
    startTime: '17:00',
    endTime: '18:00',
    category: 'sky',
    location: 'Oficina Central',
    notes: 'Vuelos y viáticos para gira comercial de fin de mes',
    reminder: '30 mins before',
  },

  // SEP 17 - Día activo en la vista Timeline (pantalla central)
  {
    id: 'ev-17-1',
    title: 'Meeting with legal team',
    date: '2026-09-17',
    startTime: '08:30',
    endTime: '10:00',
    category: 'amber',
    location: 'Sala de Juntas Piso 4',
    notes: 'Revisión de términos y garantías de contratos comerciales',
    attendees: [INITIAL_ATTENDEES[1], INITIAL_ATTENDEES[2]],
    reminder: '10 mins before',
  },
  {
    id: 'ev-17-2',
    title: 'Video call with the Amsterdam team',
    date: '2026-09-17',
    startTime: '10:15',
    endTime: '11:45',
    category: 'lavender',
    videoCall: 'Zoom - 0366971',
    location: 'En línea',
    notes: 'Sincronización de arquitectura backend y sincronización offline',
    attendees: INITIAL_ATTENDEES,
    reminder: '15 mins before',
  },
  {
    id: 'ev-17-3',
    title: 'Lunch with investors',
    date: '2026-09-17',
    startTime: '13:00',
    endTime: '14:45',
    category: 'mint',
    location: 'Restaurante Portal del Ángel',
    notes: 'Presentación de métricas de crecimiento y adopción en campo',
    attendees: [INITIAL_ATTENDEES[0], INITIAL_ATTENDEES[3]],
    reminder: '30 mins before',
  },
  {
    id: 'ev-17-4',
    title: 'Visita de seguimiento - Finca El Roble',
    date: '2026-09-17',
    startTime: '15:30',
    endTime: '17:00',
    category: 'sky',
    location: 'Km 42 Carretera al Pacífico, Escuintla',
    notes: 'Verificación de garantías prendarias e inspección física',
    personaName: 'Agrícola El Roble S.A.',
    reminder: '1 hour before',
  },

  // OCT 7
  {
    id: 'ev-oct-1',
    title: 'Book concert tickets',
    date: '2026-10-07',
    startTime: '09:00',
    endTime: '10:00',
    category: 'lavender',
    location: 'Puntos Ticket GT',
    notes: 'Preventa exclusiva para el equipo',
    reminder: '1 day before',
  },

  // NOV 23
  {
    id: 'ev-nov-1',
    title: 'Snack with Pam',
    date: '2026-11-23',
    startTime: '15:30',
    endTime: '16:30',
    category: 'sky',
    location: "Pam's Bistro",
    notes: 'Charla de mentoría y feedback de desempeño',
    attendees: [INITIAL_ATTENDEES[0]],
    reminder: '15 mins before',
  },
  {
    id: 'ev-nov-2',
    title: 'SDL Concert with Pam',
    date: '2026-11-23',
    startTime: '19:00',
    endTime: '22:00',
    category: 'amber',
    location: 'Teatro Nacional',
    notes: 'Entradas en sección B',
    reminder: '2 hours before',
  },

  // DEC 1
  {
    id: 'ev-dec-1',
    title: 'Weekend trip',
    date: '2026-12-01',
    startTime: '08:00',
    endTime: '18:00',
    category: 'rose',
    location: 'Antigua Guatemala & Lago de Atitlán',
    notes: 'Retiro y cierre anual de metas del equipo de ventas',
    attendees: INITIAL_ATTENDEES,
    reminder: '1 day before',
  },
]